title: 'Curso Intensivo de Python'
description: 'Estudos do Livro: Curso Intensivo de Python - Uma Introdução Prática e Baseada em Projetos à Programação'
show_downloads: false
google_analytics:
theme: jekyll-theme-cayman
